// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCydBZMDhTSJ9Jku7UaByoz1nK03cEtjR4',
    appId: '1:195088283002:android:3012878175077b4025d2c3',
    messagingSenderId: '195088283002',
    projectId: 'chat-f42fd',
    databaseURL: 'https://chat-f42fd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-f42fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARIhGjEhy3A3E9yTQ0VAa0Bqi8s_8RwYM',
    appId: '1:195088283002:ios:2dbd40fd93cbf8ec25d2c3',
    messagingSenderId: '195088283002',
    projectId: 'chat-f42fd',
    databaseURL: 'https://chat-f42fd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-f42fd.firebasestorage.app',
    iosBundleId: 'uz.mobildasturchi.chatApp',
  );
}
